### PR TITLE
Add links

### PR DESCRIPTION
**Pull request by saparikh**
removing documentation text until we generate and post them

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/12)* status: all files reviewed, 1 unresolved discussion (waiting on @saparikh)

___
*[README.md, line 87 at r1](https://reviewable.io/reviews/batfish/ansible/12#-LhHOScY5MaRi8yNLiie:-LhHOScY5MaRi8yNLiif:b-mpqece) ([raw file](https://github.com/batfish/ansible/blob/7d02c788cbbb17510b3dffff4ab61ef09c25a3fc/README.md#L87)):*
> ```Markdown
> 
> - Open a Github [issue](https://github.com/batfish/ansible/issues)
> - Post a question on our [Slack Group](https://batfish-org.slack.com)
> ```

Use the Slack join link here?

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/12)* status: all files reviewed, 1 unresolved discussion (waiting on @saparikh)

**Comment by saparikh** [comment]
___
*[README.md, line 87 at r1](https://reviewable.io/reviews/batfish/ansible/12#-LhHOScY5MaRi8yNLiie:-LhJ_kkY5NVHwcYlHzB4:b-896fix) ([raw file](https://github.com/batfish/ansible/blob/7d02c788cbbb17510b3dffff4ab61ef09c25a3fc/README.md#L87)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

Use the Slack join link here?
</blockquote></details>

Done.

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/12)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
