### PR TITLE
Initial Buildkite pipeline

### PR DESCRIPTION
**Pull request by sfraint**
Add initial Buildkite pipeline.  For now, this only sets up Python+Ansible and runs the tutorials to make sure they complete successfully.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/54)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @progwriter and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/54#-LhhGk7l6rQzXVdJlxa1:-LhhGk7l6rQzXVdJlxa2:bly3rta) (no related file):*
After https://github.com/batfish/ansible/pull/53

---

**Review by progwriter — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/54)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @progwriter and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/54#-Lhhcfdk2G_wZqrhJy1D:-Lhhcfdk2G_wZqrhJy1E:briljlv) (no related file):*
I see fatal errors in console logs, but the build doesn't fail. Can you explain?

https://buildkite.com/batfish/ansible-pre-commit/builds/26#6c426b43-4dbc-4096-8c31-1c38ae884fde

---
___
*[.buildkite/setup_ansible.sh, line 3 at r1](https://reviewable.io/reviews/batfish/ansible/54#-LhhctT59AXdNLZ4_GU5:-LhhctT59AXdNLZ4_GU6:b5klyqp) ([raw file](https://github.com/batfish/ansible/blob/e3653f1be19033f742ca7e658902fead7123bbcc/.buildkite/setup_ansible.sh#L3)):*
> ```Shell
> #!/usr/bin/env bash
> # Setup Ansible and our Batfish Ansible role
> set -euxo pipefail
> ```

do you need the `-x` here? gets rather verbose

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/54)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @progwriter and @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/54#-Lhhcfdk2G_wZqrhJy1D:-LhkbElr1zsD_7C34RBt:bmbgo1e) (no related file):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

I see fatal errors in console logs, but the build doesn't fail. Can you explain?

https://buildkite.com/batfish/ansible-pre-commit/builds/26#6c426b43-4dbc-4096-8c31-1c38ae884fde
</blockquote></details>

Each of the `validate_...` tutorial playbooks has a failing assertion, by design.  Each fatal failure suffixed with `...ignoring` means we set the flag in the playbook (`ignore_errors: true`) for that task to ignore the failure and proceed.

Any other failing task in the playbooks (before or after the assertion) should cause Ansible and the build to fail.

---
___
*[.buildkite/setup_ansible.sh, line 3 at r1](https://reviewable.io/reviews/batfish/ansible/54#-LhhctT59AXdNLZ4_GU5:-LhkcTE15rP8AJab7X-X:b-g5oy20) ([raw file](https://github.com/batfish/ansible/blob/e3653f1be19033f742ca7e658902fead7123bbcc/.buildkite/setup_ansible.sh#L3)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

do you need the `-x` here? gets rather verbose
</blockquote></details>

not particularly, removed

**Review by progwriter — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
