### PR TITLE
Readme updates

### PR DESCRIPTION
**Pull request by saparikh**

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/5)* status: all files reviewed, 1 unresolved discussion (waiting on @saparikh and @sfraint)

___
*[README.md, line 30 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8GLe_73_FOzXBAbCV:-Lh8GLe_73_FOzXBAbCW:b-7xhes) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L30)):*
> ```Markdown
>   gather_facts: no
>   roles:
>     - Batfish.base
> ```

lower case 'B' in Batfish.

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/5)* status: all files reviewed, 5 unresolved discussions (waiting on @saparikh)

___
*[README.md, line 25 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8G9vl5lYwkGoz2_c2:-Lh8G9vl5lYwkGoz2_c3:b-d3y1fx) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L25)):*
> ```Markdown
> ```yaml
> ---
> - name: Welcome to the first Batfish Tutorial!
> ```

You can only run this playbook once? then you have to manually stop docker?
___
*[README.md, line 34 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8GqCSCF3P65eUM4gR:-Lh8GqCSCF3P65eUM4gS:b-b5goj8) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L34)):*
> ```
> batfish_docker_start.yml
> ```
Where is this file? not yet built?
___
*[README.md, line 38 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8G4htA0B9pEYEwGom:-Lh8G4htA0B9pEYEwGon:bnu9lcs) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L38)):*
> ```
>     pause:
>       seconds: 5
> ```
This seems like a brittle way to wait for Batfish to start
___
*[README.md, line 77 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8GLr-DiGLSI2Yn-fN:-Lh8GLr-DiGLSI2Yn-fO:b5k2a6t) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L77)):*
> ```
> - PyYAML >= 3.10
> ```
Maybe just link to the `requirements.txt` for a single source of truth (seems like this could easily diverge from the deps in that file if we forget to update both)

**Comment by saparikh** [comment]
___
*[README.md, line 34 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8GqCSCF3P65eUM4gR:-Lh8H-O4AgVxZm4gslgV:bps3ajj) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L34)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> batfish_docker_start.yml
> ```
Where is this file? not yet built?
</blockquote></details>

it is in the playbooks directory

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/5)* status: all files reviewed, 5 unresolved discussions (waiting on @saparikh)

___
*[README.md, line 34 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8GqCSCF3P65eUM4gR:-Lh8H7M32zEudT8OtPRh:bbysmw5) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L34)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

it is in the playbooks directory
</blockquote></details>

there isn't a playbooks directory in this repo
___
*[README.md, line 38 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8G4htA0B9pEYEwGom:-Lh8Gxiw2u_7tsegVdrt:bxg6kkx) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L38)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
>     pause:
>       seconds: 5
> ```
This seems like a brittle way to wait for Batfish to start
</blockquote></details>

Maybe this should be part of the `batfish_docker_start.yml` file instead - and we can do something less brittle there without having to complicate our example playbook

**Comment by saparikh** [comment]
___
*[README.md, line 25 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8G9vl5lYwkGoz2_c2:-Lh8HqzW8ORjVk9Ju0Ct:bc6xc50) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L25)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

You can only run this playbook once? then you have to manually stop docker?
</blockquote></details>

No need to stop docker. The playbook checks if docker is running and then skips starting it up.

It doesn't check for a new docker image, for new images and pybatfish dependencies there is a different playbook.

But, I removed the docker start playbook reference, since in this README it is not adding value.

**Comment by saparikh** [comment]
___
*[README.md, line 34 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8GqCSCF3P65eUM4gR:-Lh8I61p61T-_XmBFFIx:b3mysjp) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L34)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

there isn't a playbooks directory in this repo
</blockquote></details>

yeah, it was in the ansible utilities repo. removed referenced

**Comment by saparikh** [comment]
___
*[README.md, line 38 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8G4htA0B9pEYEwGom:-Lh8IC3q-C9mb1gBIT0D:b-jjphwp) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L38)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Maybe this should be part of the `batfish_docker_start.yml` file instead - and we can do something less brittle there without having to complicate our example playbook
</blockquote></details>

removed from this example... but yes, it is brittle :)

Need to come up with better way to check if services is ready for connections. Docker starts and the task exists quite quickly and you need >2 seconds but <5 seconds on my machine for the service to respond to connection requests.

**Comment by saparikh** [comment]
___
*[README.md, line 77 at r1](https://reviewable.io/reviews/batfish/ansible/5#-Lh8GLr-DiGLSI2Yn-fN:-Lh8IRLx9WjL73rOp_OX:baylaz2) ([raw file](https://github.com/batfish/ansible/blob/538a0f24236089ad1478e2feccde9e786304256b/README.md#L77)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

> ```
> - PyYAML >= 3.10
> ```
Maybe just link to the `requirements.txt` for a single source of truth (seems like this could easily diverge from the deps in that file if we forget to update both)
</blockquote></details>

If we add any more dependencies, we can do that :). Should probably remove the Ansible dependency. Also, we need to pick if we want the dependency to be 2.7, 2.8 or earlier.

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
