### PR TITLE
Edits to descriptions of various assertions

### PR DESCRIPTION
**Pull request by saparikh**

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/29)* status: all files reviewed, 2 unresolved discussions (waiting on @saparikh)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/29#-LhXgQSD-x4dbp0kmCA2:-LhXgQSD-x4dbp0kmCA3:bksqlay) (no related file):*
In case it wasn't clear, you also need to regenerate docs. `make docs` in `docs` folder after documentation changes.

---
___
*[module_utils/bf_assertion_util.py, line 30 at r1](https://reviewable.io/reviews/batfish/ansible/29#-LhXgYVIE9ZVERLl8XTd:-LhXgYVIE9ZVERLl8XTe:b-64lytl) ([raw file](https://github.com/batfish/ansible/blob/479dd5712c012065f35ab10626e3661b2cf4e59b/module_utils/bf_assertion_util.py#L30)):*
> ```Python
>     short_description: Assert that all packets with specified start locations and headers fail
>     description:
>         - "This is an all-to-all test."
> ```

`This is an all-to-all test that analyzes all (start location, header) combinations.`?

(same for the other one.)

**Comment by saparikh** [comment]
___
*[module_utils/bf_assertion_util.py, line 30 at r1](https://reviewable.io/reviews/batfish/ansible/29#-LhXgYVIE9ZVERLl8XTd:-LhXgz_Z3809ZqMLMieU:b-ker33q) ([raw file](https://github.com/batfish/ansible/blob/479dd5712c012065f35ab10626e3661b2cf4e59b/module_utils/bf_assertion_util.py#L30)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

`This is an all-to-all test that analyzes all (start location, header) combinations.`?

(same for the other one.)
</blockquote></details>

that makes sense, will update.

**Review by ratulm — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/29)* status: all files reviewed, 2 unresolved discussions (waiting on @ratulm and @saparikh)

**Comment by saparikh** [comment]
A follow-on PR incorporates these changes.

**Pull request closed without merging**
