### PR TITLE
Add diagnostics playbook

### PR DESCRIPTION
**Pull request by sfraint**
Add diagnostics playbook

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/41)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ratulm and @saparikh)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/41#-Lhc84gk4GtqhlNwL-NK:-Lhc84gk4GtqhlNwL-NL:bjxzz33) (no related file):*
Opinions on how to surface this to the user? Add another bullet in the tutorials main section?

---

**Comment by saparikh** [comment]
*[a discussion](https://reviewable.io/reviews/batfish/ansible/41#-Lhc84gk4GtqhlNwL-NK:-LhcDxYv3vtv0WQjSpIt:b-22m1rl) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Opinions on how to surface this to the user? Add another bullet in the tutorials main section?
</blockquote></details>

We should add a pointer in the tutorials README.

In the module doc, we should call out the default Netconan behavior

---

**Review by saparikh — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/41)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm and @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/41)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ratulm and @saparikh)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/41#-Lhc84gk4GtqhlNwL-NK:-LhcIq4c-hio0XRONl8E:bnvfu8o) (no related file):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

We should add a pointer in the tutorials README.

In the module doc, we should call out the default Netconan behavior
</blockquote></details>

How does that look @saparikh ?

---

**Comment by saparikh** [comment]
___
*[module_utils/bf_util.py, line 68 at r2](https://reviewable.io/reviews/batfish/ansible/41#-LhcJVSfChs_ma-IHiXw:-LhcJVSfChs_ma-IHiXx:b-cms3my) ([raw file](https://github.com/batfish/ansible/blob/5acd984fa6ff4f8161587f1a2315dda65510c0d6/module_utils/bf_util.py#L68)):*
> ```Python
>     statuses = get_snapshot_parse_status(session)
>     if check_if_any_failed(statuses):
>         return 'Your snapshot was initialized but Batfish failed to parse one or more input files. You can proceed but some analyses may be incorrect. You can help the Batfish developers improve support for your network by running the bf_upload_diagnostics module: {}'.format(_UPLOAD_DIAGNOSTICS_DOC_URL)
> ```

shouldn't it be `analysis`?

**Comment by saparikh** [comment]
___
*[tutorials/README.md, line 15 at r2](https://reviewable.io/reviews/batfish/ansible/41#-LhcJab9AtIxn_Ahza_M:-LhcJab9AtIxn_Ahza_N:b59spoi) ([raw file](https://github.com/batfish/ansible/blob/5acd984fa6ff4f8161587f1a2315dda65510c0d6/tutorials/README.md#L15)):*
> ```Markdown
> - **bf_tutorial_5.yml**: Shows you how to validate configuration attributes to find mis-configured BGP sessions and undefined references
> 
> - **bf_upload_diagnostics**: Shows you how you can upload diagnostic information about your snapshot in the event of issues (e.g. if Batfish fails to fully recognized some lines in your input files)
> ```

- add `.yml` to the name to keep with the convention of the other tutorials.
- `Shows you how to upload diagnostic...`

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/41)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @ratulm and @saparikh)

___
*[module_utils/bf_util.py, line 68 at r2](https://reviewable.io/reviews/batfish/ansible/41#-LhcJVSfChs_ma-IHiXw:-LhcKlFv0qlsTohQEj9n:bvnrpcm) ([raw file](https://github.com/batfish/ansible/blob/5acd984fa6ff4f8161587f1a2315dda65510c0d6/module_utils/bf_util.py#L68)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

shouldn't it be `analysis`?
</blockquote></details>

updated
___
*[tutorials/README.md, line 15 at r2](https://reviewable.io/reviews/batfish/ansible/41#-LhcJab9AtIxn_Ahza_M:-LhcKc-IDG0FJuwtZFKk:b-7ql1td) ([raw file](https://github.com/batfish/ansible/blob/5acd984fa6ff4f8161587f1a2315dda65510c0d6/tutorials/README.md#L15)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

- add `.yml` to the name to keep with the convention of the other tutorials.
- `Shows you how to upload diagnostic...`
</blockquote></details>

fixed

**Review by saparikh — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/41#-:-LhcM4dNEtnN3_y8DvNO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ratulm)

**Pull request merged**
