### PR TITLE
Add initial plugins and modules

### PR DESCRIPTION
**Pull request by sfraint**
Add initial plugins and modules used in `Batfish` Ansible role.

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/2)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @ratulm and @saparikh)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/2#-Lh7c5V6CD3fbjleoufS:-Lh7c5V6CD3fbjleoufT:brbjedl) (no related file):*
A few notes:
* today, we're stuck at ~1 plugin per module and our common-code-reuse across plugins is not good - solution is TBD
* `bf_assert` module, examples, testing, and more cleanup to come

---

**Comment by saparikh** [comment]
___
*[library/bf_extract_facts.py, line 1 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7frF03A4fkUyH55BR:-Lh7frF03A4fkUyH55BS:biuvbfo) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L1)):*
> ```Python
> #!/usr/bin/python
> ```

Do we need this here? Will this prevent Ansible from use the `ansible_python_interpeter` inventory variable?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/2)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @ratulm and @saparikh)

___
*[library/bf_extract_facts.py, line 1 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7frF03A4fkUyH55BR:-Lh7gujN5nDkMsvZmQWA:bd3k0t2) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L1)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

Do we need this here? Will this prevent Ansible from use the `ansible_python_interpeter` inventory variable?
</blockquote></details>

Shouldn't affect their ability to run different version of Python.  It was copied from the [Ansible module creation guide](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#starting-a-new-module)'s example module code.

**Review by ratulm — COMMENTED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/2#-:-Lh7m80c59fMg23zq0g2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by saparikh** [comment]
___
*[library/bf_extract_facts.py, line 75 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7m24jEHR7bp9CwP0S:-Lh7m24jEHR7bp9CwP0T:b-xts7fu) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L75)):*
> ```Python
>     contains:
>         nodes:
>             description: Dictionary of node-name to node-facts for each node.
> ```

We should add a pointer to a GH page that has a sample fact file here. This way users can see the keys and hierarchy without having to run extraction first

**Comment by saparikh** [comment]
___
*[library/bf_extract_facts.py, line 1 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7frF03A4fkUyH55BR:-Lh7mLzOCbOjRwyPZFY8:b13gbxh) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L1)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

Shouldn't affect their ability to run different version of Python.  It was copied from the [Ansible module creation guide](https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#starting-a-new-module)'s example module code.
</blockquote></details>

Ok, is there a reason why the action plugins don't have this then?

**Comment by saparikh** [comment]
___
*[library/bf_extract_facts.py, line 75 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7m24jEHR7bp9CwP0S:-Lh7my2l0QBWa4n7cC8Z:b-g586m2) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L75)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

We should add a pointer to a GH page that has a sample fact file here. This way users can see the keys and hierarchy without having to run extraction first
</blockquote></details>

We can do this later on, this is not a blocking comment. We should just add it to our to-do list

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/2)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

___
*[library/bf_extract_facts.py, line 1 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7frF03A4fkUyH55BR:-Lh7mqqT4OkE5MCJYdLz:b-nbdqol) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L1)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

Ok, is there a reason why the action plugins don't have this then?
</blockquote></details>

not really, in some of their docs they have that line but in other places they don't
___
*[library/bf_extract_facts.py, line 75 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7m24jEHR7bp9CwP0S:-Lh7mzeGC1X50aUHtagP:b-kmk3es) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L75)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

We should add a pointer to a GH page that has a sample fact file here. This way users can see the keys and hierarchy without having to run extraction first
</blockquote></details>

will do, once we have that :stuck_out_tongue:

**Review by sfraint — COMMENTED** [review]
> Reviewed 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/2)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by saparikh** [comment]
___
*[library/bf_extract_facts.py, line 1 at r1](https://reviewable.io/reviews/batfish/ansible/2#-Lh7frF03A4fkUyH55BR:-Lh7pojcDxbm7ROcvKtq:bl2d339) ([raw file](https://github.com/batfish/ansible/blob/0cd8710780568862301af45f7ccb486cbb5b3824/library/bf_extract_facts.py#L1)):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

not really, in some of their docs they have that line but in other places they don't
</blockquote></details>

Ok, we should just be consistent and just exclude it everywhere

**Comment by saparikh** [comment]
___
*[library/bf_extract_facts.py, line 60 at r3](https://reviewable.io/reviews/batfish/ansible/2#-Lh7rsKT4MfsyGSMVHwj:-Lh7rsKU0gaQEfYlaEAs:b-iep4ta) ([raw file](https://github.com/batfish/ansible/blob/17b48d54a7588374032b1c41bb7ae53b059cb105/library/bf_extract_facts.py#L60)):*
> ```Python
> # Extract facts and save to an output directory
> - bf_extract_facts:
>     output_directory: output/facts/
> ```

When this module is invoked, can or will it create this directory if it does not exist?

**Pull request merged**
