### PR TITLE
minor tweaks to documentation

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Comment by saparikh** [comment]
___
*[docs/bf_validate_facts.rst, line 80 at r1](https://reviewable.io/reviews/batfish/ansible/28#-LhXcSkg0LS6OR4PmerH:-LhXcSkh7Twqg2LR8UMn:b-mdywj7) ([raw file](https://github.com/batfish/ansible/blob/75866f71fedacdf5bfc14463cfc96d705ede9b91/docs/bf_validate_facts.rst#L80)):*
> ```reStructuredText
>     <td>dict</td>
>     <td>no</td>
>     <td>Value in the <code>bf_session</code> fact.</td>
> ```

This change should be made in the other files as well.

**Review by saparikh — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/28)* status: all files reviewed, 1 unresolved discussion (waiting on @ratulm and @sfraint)

**Review by ratulm — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/28)* status: all files reviewed, 1 unresolved discussion (waiting on @saparikh and @sfraint)

___
*[docs/bf_validate_facts.rst, line 80 at r1](https://reviewable.io/reviews/batfish/ansible/28#-LhXcSkg0LS6OR4PmerH:-LhXdDQ5DqMNP3SLm-zX:bzh5byt) ([raw file](https://github.com/batfish/ansible/blob/75866f71fedacdf5bfc14463cfc96d705ede9b91/docs/bf_validate_facts.rst#L80)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

This change should be made in the other files as well.
</blockquote></details>

The change was adding "the". Other places already have it. Do you spot an inconsistency?

**Comment by saparikh** [comment]
___
*[docs/bf_validate_facts.rst, line 80 at r1](https://reviewable.io/reviews/batfish/ansible/28#-LhXcSkg0LS6OR4PmerH:-LhXg8_P1S3Otg6Lrr5a:b-fez1cc) ([raw file](https://github.com/batfish/ansible/blob/75866f71fedacdf5bfc14463cfc96d705ede9b91/docs/bf_validate_facts.rst#L80)):*
<details><summary><i>Previously, ratulm wrote…</i></summary><blockquote>

The change was adding "the". Other places already have it. Do you spot an inconsistency?
</blockquote></details>

init_snapshot, extract_facts is missing 'the' in the `session` row

**Review by saparikh — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/28#-:-LhXhl8F0s456enbTJKa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Pull request merged**
