### PR TITLE
Add testing for more Python versions

### PR DESCRIPTION
**Pull request by sfraint**
Add testing for more Python versions

Note, had to make a couple changes to get tests to work in Python 2
  * Return fact validation results as a dict instead of list of dicts
  * Use more general `Exception` type + exception message where exception type differs between Python 2 and 3
* Convert some path objects to strings (in tests)

### CODE REVIEW

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/60)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @sfraint)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/60#-LiAhA5j2lkaIkmVw3HN:-LiAhA5j2lkaIkmVw3HO:bly3rtg) (no related file):*
After https://github.com/batfish/ansible/pull/59

---

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/60)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @progwriter)

*[a discussion](https://reviewable.io/reviews/batfish/ansible/60#-LiAhA5j2lkaIkmVw3HN:-LiAhtvY6DTpcNYqhSfa:bkqfys) (no related file):*
<details><summary><i>Previously, sfraint (Spencer Fraint) wrote…</i></summary><blockquote>

After https://github.com/batfish/ansible/pull/59
</blockquote></details>

Ready now

---

**Review by progwriter — COMMENTED** [review]
> Reviewed 10 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/60)* status: all files reviewed, 2 unresolved discussions (waiting on @sfraint)

___
*[module_utils/bf_util.py, line 329 at r2](https://reviewable.io/reviews/batfish/ansible/60#-LiAnQ1S3QDN1fgNOa3S:-LiAnQ1S3QDN1fgNOa3T:b-kpox2t) ([raw file](https://github.com/batfish/ansible/blob/152907e7d25690bd945fdbf2b4c4140d1542078b/module_utils/bf_util.py#L329)):*
> ```Python
>                         'actual': actual[k],
>                     }
>     return diffs_out
> ```

that's a breaking change, right? what was problematic with previous output?
___
*[tests/unit/test_facts.py, line 90 at r2](https://reviewable.io/reviews/batfish/ansible/60#-LiAmv__EnnDNVQPGm9J:-LiAmv__EnnDNVQPGm9K:b-l7z1c9) ([raw file](https://github.com/batfish/ansible/blob/152907e7d25690bd945fdbf2b4c4140d1542078b/tests/unit/test_facts.py#L90)):*
> ```Python
>     f.write('foo')
>     # File instead of dir should throw exception indicating such
>     with pytest.raises(Exception) as e_not_dir:
> ```

`OsError`

**Review by progwriter — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/60)* status: all files reviewed, 1 unresolved discussion (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/60)* status: all files reviewed, 1 unresolved discussion (waiting on @progwriter)

___
*[module_utils/bf_util.py, line 329 at r2](https://reviewable.io/reviews/batfish/ansible/60#-LiAnQ1S3QDN1fgNOa3S:-LiAy9rp3-uV-WxaouLS:b6x4cxw) ([raw file](https://github.com/batfish/ansible/blob/152907e7d25690bd945fdbf2b4c4140d1542078b/module_utils/bf_util.py#L329)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

that's a breaking change, right? what was problematic with previous output?
</blockquote></details>

Iteration order of keys (property names) was inconsistent, so the output list elements were not consistently ordered.  Also the output was unnecessarily bulky.

Like we talked about offline, we're okay with making this change today.  Seems like now is best time to make this change while there is minimal dependence on the current output format
___
*[tests/unit/test_facts.py, line 90 at r2](https://reviewable.io/reviews/batfish/ansible/60#-LiAmv__EnnDNVQPGm9J:-LiAypKE4YTHGJIvfRUD:b-bw8e14) ([raw file](https://github.com/batfish/ansible/blob/152907e7d25690bd945fdbf2b4c4140d1542078b/tests/unit/test_facts.py#L90)):*
<details><summary><i>Previously, progwriter (Victor Heorhiadi) wrote…</i></summary><blockquote>

`OsError`
</blockquote></details>

Updated.

**Pull request merged**
