### PR TITLE
adding docs

### PR DESCRIPTION
**Pull request by ratulm**

### CODE REVIEW

**Review by saparikh — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 12 files at r1, 6 of 14 files at r2, 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/16#-:-LhNAv6W0i23iizKRsFD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sfraint)

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/16)* status: all files reviewed, 4 unresolved discussions (waiting on @ratulm)

___
*[docs/bf_assert.rst, line 44 at r2](https://reviewable.io/reviews/batfish/ansible/16#-LhN8Y88CF1CJJcyIvON:-LhN8Y88CF1CJJcyIvOO:b-xost5s) ([raw file](https://github.com/batfish/ansible/blob/bf08a98e7d9b5834a509b38269ed1c9a92f003aa/docs/bf_assert.rst#L44)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     <th class="head">parameter</th>
>     <th class="head">type</th>
>     <th class="head">required</th>
>     <th class="head">default</th>
>     <th class="head">choices</th>
>     <th class="head">comments</th>
> ```
</details>

Any point to having all these columns in the input-documentation-table when we only ever fill out two of them?  Should we simplify the table here? or fill out more details about the input params?
___
*[library/bf_assert.py, line 45 at r2](https://reviewable.io/reviews/batfish/ansible/16#-LhNAKQE3YKocE-5x1mm:-LhNAKQE3YKocE-5x1mn:b5a8sr) ([raw file](https://github.com/batfish/ansible/blob/bf08a98e7d9b5834a509b38269ed1c9a92f003aa/library/bf_assert.py#L45)):*
> ```
> parameters 
> ```
Like we talked about, don't call it "parameters" here since that could be confusing since we have a session `parameters` key when building the session.
Same comment applies to other modules that also take in a session (all but `bf_session`)
___
*[library/bf_session.py, line 42 at r2](https://reviewable.io/reviews/batfish/ansible/16#-LhNA40Y-IsqO0fSOAnm:-LhNA40Y-IsqO0fSOAnn:bo3ci6p) ([raw file](https://github.com/batfish/ansible/blob/bf08a98e7d9b5834a509b38269ed1c9a92f003aa/library/bf_session.py#L42)):*
> ```
> {ssl: true}
> ```
Any reason not to put this in `C(...)` for formatting
___
*[library/bf_session.py, line 80 at r2](https://reviewable.io/reviews/batfish/ansible/16#-LhN9umm54HqHFKQRt9F:-LhN9umm54HqHFKQRt9G:b-3lirc7) ([raw file](https://github.com/batfish/ansible/blob/bf08a98e7d9b5834a509b38269ed1c9a92f003aa/library/bf_session.py#L80)):*
> ```
> ·············
> ```
nit: delete trailing whitespace

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/16)* status: all files reviewed, 5 unresolved discussions (waiting on @ratulm)

___
*[docs/bf_session.rst, line 76 at r3](https://reviewable.io/reviews/batfish/ansible/16#-LhNBoxx9zflGkg2XzXO:-LhNBoxx9zflGkg2XzXP:b-ig769a) ([raw file](https://github.com/batfish/ansible/blob/e7b127fe1317f1da4fc4778af69ae3a216e3d0f2/docs/bf_session.rst#L76)):*
> ```
> {&#x27;Dictionary with additional parameters used to configure the session. Use {ssl&#x27;: &#x27;true} to use SSL.&#x27;}
> ```
This formatting is weird, with curly braces enclosing the description

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/16)* status: all files reviewed, 6 unresolved discussions (waiting on @ratulm)

___
*[library/bf_session.py, line 80 at r3](https://reviewable.io/reviews/batfish/ansible/16#-LhNC3ZPDsSdwMdiHiBi:-LhNC3ZQ2wi609RShgNT:b-zgchx1) ([raw file](https://github.com/batfish/ansible/blob/e7b127fe1317f1da4fc4778af69ae3a216e3d0f2/library/bf_session.py#L80)):*
> ```
> always
> ```

> ```
> If supplied by user
> ```
We should be consistent about casing - capitalize the first letter or don't for when things are returned

**Pull request merged**
