### PR TITLE
Add bf_assert module and plugin

### PR DESCRIPTION
**Pull request by sfraint**
Add initial `bf_assert` module and plugin.

### CODE REVIEW

**Review by ratulm — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @saparikh)

**Comment by saparikh** [comment]
___
*[library/bf_assert.py, line 69 at r1](https://reviewable.io/reviews/batfish/ansible/8#-LhDAXdHB0PNt97-msKq:-LhDAXdHB0PNt97-msKr:b-tvacmj) ([raw file](https://github.com/batfish/ansible/blob/19515511ecbb66498ebc1d7a63fc8f7aa5bd019b/library/bf_assert.py#L69)):*
> ```Python
>         name: confirm node1 filter block_access denies TCP traffic on port 22
>         parameters:
>           filter_name: 'node1["block_access"]'
> ```

Are the single quotes needed here?

**Review by sfraint — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/8)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ratulm and @saparikh)

___
*[library/bf_assert.py, line 69 at r1](https://reviewable.io/reviews/batfish/ansible/8#-LhDAXdHB0PNt97-msKq:-LhDCXJUDSEPIUmnt_gZ:b-b5gvfu) ([raw file](https://github.com/batfish/ansible/blob/19515511ecbb66498ebc1d7a63fc8f7aa5bd019b/library/bf_assert.py#L69)):*
<details><summary><i>Previously, saparikh (Samir Parikh) wrote…</i></summary><blockquote>

Are the single quotes needed here?
</blockquote></details>

like we discussed, will just single quote all our input parameters for consistency and safety

**Review by sfraint — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/batfish/ansible/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
